// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SantoAndreOnBus.Contexts;

namespace SantoAndreOnBus.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190731185123_LinesAndInterestPointsAdded")]
    partial class LinesAndInterestPointsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SantoAndreOnBus.Models.InterestPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LineId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("InterestPoints");
                });

            modelBuilder.Entity("SantoAndreOnBus.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Backwards");

                    b.Property<string>("Fromwards");

                    b.Property<string>("Letter");

                    b.Property<string>("Number");

                    b.Property<int>("PeakHeadway");

                    b.HasKey("Id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("SantoAndreOnBus.Models.InterestPoint", b =>
                {
                    b.HasOne("SantoAndreOnBus.Models.Line", "Line")
                        .WithMany("InterestPoints")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
