// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SantoAndreOnBus.Contexts;

namespace SantoAndreOnBus.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190806200444_CompaniesAdded")]
    partial class CompaniesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SantoAndreOnBus.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SantoAndreOnBus.Models.InterestPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LineId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("InterestPoints");
                });

            modelBuilder.Entity("SantoAndreOnBus.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyId");

                    b.Property<string>("Fromwards");

                    b.Property<string>("Letter");

                    b.Property<string>("Number");

                    b.Property<int>("PeakHeadway");

                    b.Property<string>("Towards");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("SantoAndreOnBus.Models.InterestPoint", b =>
                {
                    b.HasOne("SantoAndreOnBus.Models.Line", "Line")
                        .WithMany("InterestPoints")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SantoAndreOnBus.Models.Line", b =>
                {
                    b.HasOne("SantoAndreOnBus.Models.Company", "Company")
                        .WithMany("Lines")
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
