spring:
  application:
    name: scraper
  datasource:
    url: jdbc:sqlite:Database.db
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

info:
  title: BusCatalog.Scraper

configuration:
  emtu:
    identificationUrl: https://www.emtu.sp.gov.br/Sistemas/linha/resultado.htm?numlinha=@id&pag=buscanumero.htm
    dataUrl: https://www.emtu.sp.gov.br/sistemas/linha/resultado_imp.htm?numlinha=
  apiUrl: http://localhost:5262
  linesProducer:
    topic: public.lines.sync
    bootstrapServers: localhost:9092
  description:
    title: BusCatalog.Scraper
    version: "1.0"
    description: This API fetches data from transport authorities and provides ways to synchronize them with BusCatalog.Api.