spring:
  application:
    name: scraper
  datasource:
    url: jdbc:sqlite:bus-catalog-scraper.db
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

info:
  title: BusCatalog.Scraper

configuration:
  emtu:
    identificationUrl: https://www.emtu.sp.gov.br/Sistemas/linha/resultado.htm?numlinha=@id&pag=buscanumero.htm
    dataUrl: https://www.emtu.sp.gov.br/sistemas/linha/resultado_imp.htm?numlinha=
  busCatalog:
    url: http://localhost:5001